apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-zen-operator
  namespace: cp4ba-project
spec:
  channel: <new-channel>
  name: ibm-zen-operator
  source: <new-catalog-name>
  sourceNamespace: cp4ba-project