apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parentapplication
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: <GIT_REPO_URL>
    path: cp4ba-manifests/setup/childapplication
    targetRevision: main
  destination:
    server: <SERVER>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: