apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-namespace-scope-operator
  namespace: cp4ba-project
spec:
  channel: v4.2 # Defined in cert-kubernetes/scripts/cpfs/installer_scripts/cp3pt0-deployment/setup_tenant.sh as MAINTAINED_CHANNEL
  installPlanApproval: Automatic
  name: ibm-namespace-scope-operator
  source: ibm-cs-install-catalog-v4-16-0 # Defined in cert-kubernetes/scripts/helper/common.sh as CS_CATALOG_VERSION
  sourceNamespace: cp4ba-project
